spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoppingDb
    name: userService
    username: root2
    password: software
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userService
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        
server:
  port: 5002
    
eureka:
  instance:
    hostname: localhost